### ISSUE TITLE
Create a wrapper micro service around charity rating services

### ISSUE THREAD

**Issue by RaoBhethanabotla** [saayam-for-all/volunteerorg#1]
We need a wrapper micro service that wraps the API from all charity rating organizations like Charity Navigator. Whenever any other internal micro service needs information about volunteer organizations, they use this micro service to get this information. For e.g. when we need a list of volunteer organizations that deal with eye related issues, Request micro service will use VolunteerOrg micro service to get the list of all volunteer organizations that work in the eye related area. Then, VolunteerOrg micro service will make a request on Charity Navigator and other external services to get this list, compile and provide the list of best volunteer organizations to Request micro service.

**Comment by adi0546** [comment]
### Tasks related to this issue
- [x] [Complete core API initialisation.](https://github.com/saayam-for-all/volunteerorg/issues/4)
- [x] [Handle the incoming request to fetch list of orgs from chaityNavigator]
- [ ] [Complete Unit tests, Create executable and containerize the executable]
- [x] [Create API documentation using Swagger]

**Comment by Shashwenth** [comment]
1. API calls to Charity Navigator API is working
2. Provided the Schema to Create a DB to store this Data.
